### PR TITLE
feat: add python 3.12 support

### PR DESCRIPTION
**Pull request by ichintanjoshi**
## Description 

This PR contains changes for upgrading python 3.8 to python 3.12.

Changes include :-
- Dependencies and version upgrades
- Extra check for fractional function to get only integers
    - This is done because `fractions` function in miller.py file used `fr.gcd`
    - Since python 3.9: The [math.gcd()](https://docs.python.org/3/library/math.html#math.gcd) function is now used to normalize the numerator and denominator. [math.gcd()](https://docs.python.org/3/library/math.html#math.gcd) always return a [int](https://docs.python.org/3/library/functions.html#int) type. Previously, the GCD type depended on numerator and denominator
- Removal of 3.8 from tox file

Done as a part of this issue https://github.com/openedx/public-engineering/issues/233

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ichintanjoshi! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

File: chem/miller.py [hunk 1]
```diff
@@ -18,9 +18,10 @@ def lcm(a, b):
         a, b: floats
 
     Returns:
-        float
+        int: Because math.gcd will only return int after python 3.9
+        Previously it depended on type of args, now it'll only return int
     """
-    return a * b / fr.gcd(a, b)
+    return a * b / math.gcd(int(a), int(b))
```
Comment (ichintanjoshi) [inline chem/miller.py:24]: I am not sure if this is the right way to do it, can anyone else take a look into this ? 

Had to change from `fr.gcd` to `math.gcd` because since python 3.9 it Fractions no longer support gcd and it has been moved to `math`  [https://docs.python.org/3/library/fractions.html] (ref)

**Comment by mphilbrick211** [comment]
@openedx/2u-tnl @openedx/teaching-and-learning Hi there! Would someone be able to review this for us? Thanks!

**Comment by jristau1984** [comment]
Hi @mphilbrick211 - T&L has relinquished ownership of this repo.  Ownership updates are now reflected in the newly added "Repo Maintainer" column of the Tech Ownership sheet.  Please don't hesitate to reach out with any questions, or ideas on how to better evangelize these updates.  Thanks!

File: .github/workflows/ci.yml [hunk 2]
```diff
@@ -16,7 +16,6 @@ jobs:
       matrix:
         os: [ubuntu-20.04]
         python-version:
-        - '3.8'
```
[the remark this answers is not in the document]
Comment (ichintanjoshi) [reply .github/workflows/ci.yml:19]: Okay, so with 3.8 workflow what's happening is a conflict in `numpy`, because we've updated all the versions. 

Something like what's happening here https://github.com/openedx/openedx-calc/actions/runs/8231433530/job/22568231165?pr=99#step:7:11 

So should I downgrade numpy version and check if that'll work with both 3.8 and 3.12 ?

[the remark this answers is not in the document]
Comment (feanil) [reply .github/workflows/ci.yml:19]: Normally you can add a version of numpy that will work with both versions to `https://github.com/openedx/openedx-chem/blob/master/requirements/constraints.txt` along with a comment that we can remove the constraint once the 3.8 testing is removed.

With the numpy package in particular, it may make more sense to add it here: https://raw.githubusercontent.com/edx/edx-lint/master/edx_lint/files/common_constraints.txt since we use it in many packages across our ecosystem.

[the remark this answers is not in the document]
Comment (ichintanjoshi) [reply .github/workflows/ci.yml:19]: @feanil current version of numpy with python 3.8 is `1.23.x` here as well as in https://github.com/openedx/openedx-calc/pull/99  and it's being upgraded to `1.26.4`. 

I manually tried to find a common version between them, python 3.8 will support till `numpy==1.24.x` and if we do try to install it with python 3.12, it will give `AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?`  This error comes as a result of 3.12 removing `ImpImporter` [ref](https://docs.python.org/3/whatsnew/3.12.html#importlib:~:text=importlib.abc.Finder%2C%20pkgutil.ImpImporter%2C%20and%20pkgutil.ImpLoader%20have%20been%20removed.%20(Contributed%20by%20Barry%20Warsaw%20in%20gh%2D98040.)) or it could be because numpy depends on old pip.  Also I tried to look into numpy notes but could not find an overlap with a version that'd support 3.8 and 3.12

with python 3.8, numpy maximum version supported is 1.24.4 
and with python 3.12, numpy minimum version supported is 1.26.0 [numpy news](https://numpy.org/news/)

[the remark this answers is not in the document]
Comment (feanil) [reply .github/workflows/ci.yml:19]: Yea, I noticed this as well in a different spot that pulls numpy.  Given the importance of the package, I think we'll have to target 3.11 for edx-platform and its dependencies first and then do the 3.12 upgrade in the future.

[the remark this answers is not in the document]
Comment (ichintanjoshi) [reply .github/workflows/ci.yml:19]: Hi @feanil  okay, so should I raise another similar PR ? with 3.11 support right ?

[the remark this answers is not in the document]
Comment (feanil) [reply .github/workflows/ci.yml:19]: I think a separate PR to add testing for 3.11 and fixing any bugs that causes makes the most sense I think.

**Comment by openedx-webhooks** [comment]
@ichintanjoshi Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-chem&entry.867055334=https://github.com/openedx/openedx-chem/pull/76&entry.1484655318=https://github.com/ichintanjoshi&entry.752974735=2024-03-11+08:27&entry.1917517419=2024-03-28+12:53&entry.2133058324=No) so we can improve your experience in the future.
